---
loki:
  loki:
    auth_enabled: false
    # https://grafana.com/docs/loki/latest/operations/storage/schema/
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
  minio:
    enabled: true
    replicas: 4
    drivesPerNode: 1
  write:
    persistence:
      size: 2Gi
  read:
    persistence:
      size: 2Gi
  backend:
    persistence:
      size: 2Gi
  singlebinary:
    persistence:
      size: 2Gi
