---
loki:
  useTestSchema: true # TODO: use proper schema?
  minio:
    enabled: true
    replicas: 4
    drivesPerNode: 1
  loki:
    auth_enabled: false
  write:
    persistence:
      size: 2Gi
  read:
    persistence:
      size: 2Gi
  backend:
    persistence:
      size: 2Gi
  singlebinary:
    persistence:
      size: 2Gi
