---
redis-ha:
  enabled: true
controller:
  replicas: 1
server:
  replicas: 2
repoServer:
  replicas: 2
applicationSet:
  replicaCount: 2

argocd-as-dependency:
  redis-ha:
    enabled: true
  controller:
    replicas: 1
  server:
    replicas: 2
  repoServer:
    replicas: 2
  applicationSet:
    replicaCount: 2
