---
redis-ha:
  enabled: true
controller:
  replicas: 1
server:
  replicas: 2
repoServer:
  replicas: 2
applicationSet:
  replicaCount: 2
configs:
  params:
    # tls is handled by ingress controller
    server.insecure: true

argocd-as-dependency:
  redis-ha:
    enabled: true
  controller:
    replicas: 1
  server:
    replicas: 2
  repoServer:
    replicas: 2
  applicationSet:
    replicaCount: 2
  configs:
    params:
      # tls is handled by ingress controller
      server.insecure: true
