{{- range $namespace := .Values.namespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-intranet
  namespace: {{ $namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.5.0.0/16
  - to:
    - ipBlock:
        cidr: 10.5.150.1/32
    - ipBlock:
        cidr: 10.5.150.2/32
    - ipBlock:
        cidr: 10.5.150.3/32
    - ipBlock:
        cidr: 10.5.150.11/32
    - ipBlock:
        cidr: 10.5.150.12/32
    - ipBlock:
        cidr: 10.5.150.13/32
    - ipBlock:
        cidr: 10.5.150.14/32
    # ports:
    # - port: 6443  # kubeapi
    #   protocol: TCP
    # - port: 10250 # metrics server
    #   protocol: TCP
{{- end }}
