---
zk_kvm_hosts:
  hosts:
    dell:
      connection_user: root
      ansible_host: 10.5.0.100
      zk_kvm_data_dir: /zk-data
      zk_kvm_zvol_parent: zroot/zk
      zk_kvm_memballoon_mem_limit_mb: 16000
      zk_kvm_networks:
        - name: br105
          subnet: 10.5.0.0/16
          nic_type: bridge
          nic_source: br105
          nic_device_model: virtio
          nic_bus: 13
          netplan:
            dhcp4: false
            dhcp6: false
            routes:
              - to: 0.0.0.0/0
                via: 10.5.0.1
            nameservers:
              addresses:
                - 1.1.1.1

infra:
  hosts:
    r2d2:
      ansible_host: 10.5.0.10
      zk_vm_name: r2d2
      zk_vm_image: debian12
      zk_vm_kvm_hosts: dell
      zk_vm_memory_mb: 2000
      zk_vm_vcpus: 1
      zk_vm_disks:
        - name: r2d2-root
          dev: vda
          size: 20G
      zk_vm_networks:
        - name: br105
          netplan:
            addresses: [10.5.0.10/16]

k8s-prod:
  children:
    k8s-prod-controllers:
      vars:
        zk_vm_image: debian12
        zk_vm_memory_mb: 3000
        zk_vm_vcpus: 1
        zk_vm_disks:
          - name: "{{ zk_vm_name }}-root"
            dev: vda
            size: 40G
      hosts:
        k8s-prod-controller1:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.1
          zk_vm_name: k8s-prod-controller1
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.1/16]
        k8s-prod-controller2:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.2
          zk_vm_name: k8s-prod-controller2
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.2/16]
        k8s-prod-controller3:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.3
          zk_vm_name: k8s-prod-controller3
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.3/16]
    k8s-prod-workers:
      vars:
        zk_vm_image: debian12
        zk_vm_memory_mb: 6000
        zk_vm_vcpus: 1
        zk_vm_disks:
          - name: "{{ zk_vm_name }}-root"
            dev: vda
            size: 100G
      hosts:
        k8s-prod-worker1:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.11
          zk_vm_name: k8s-prod-worker1
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.11/16]
        k8s-prod-worker2:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.12
          zk_vm_name: k8s-prod-worker2
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.12/16]
        k8s-prod-worker3:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.13
          zk_vm_name: k8s-prod-worker3
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.13/16]
        k8s-prod-worker4:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.14
          zk_vm_name: k8s-prod-worker4
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.14/16]

k8s-dev:
  children:
    k8s-dev-controllers:
      vars:
        zk_vm_image: debian12
        zk_vm_memory_mb: 3000
        zk_vm_vcpus: 1
        zk_vm_disks:
          - name: "{{ zk_vm_name }}-root"
            dev: vda
            size: 40G
      hosts:
        k8s-dev-controller1:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.151.1
          zk_vm_name: k8s-dev-controller1
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.151.1/16]
        k8s-dev-controller2:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.151.2
          zk_vm_name: k8s-dev-controller2
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.151.2/16]
        k8s-dev-controller3:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.151.3
          zk_vm_name: k8s-dev-controller3
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.151.3/16]
    k8s-dev-workers:
      vars:
        zk_vm_image: debian12
        zk_vm_memory_mb: 6000
        zk_vm_vcpus: 1
        zk_vm_disks:
          - name: "{{ zk_vm_name }}-root"
            dev: vda
            size: 100G
      hosts:
        k8s-dev-worker1:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.151.11
          zk_vm_name: k8s-dev-worker1
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.151.11/16]
        k8s-dev-worker2:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.151.12
          zk_vm_name: k8s-dev-worker2
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.151.12/16]
        k8s-dev-worker3:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.151.13
          zk_vm_name: k8s-dev-worker3
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.151.13/16]
        k8s-dev-worker4:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.151.14
          zk_vm_name: k8s-dev-worker4
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.151.14/16]

