---
all:
  vars:
    ansible_user: root
    ansible_connection: ssh
    zk_vm_hostname: "{{ zk_vm_name }}"
    zk_vm_disk_default_zvol_parent: zroot/zk

    # Default vm root keys
    zk_vm_users:
      - name: root
        ssh_keys:
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDfYcHdLQR7LEBaVHlmg2sLJOmcn0QuADsKg3Zz83CXT9v/TmaSv7zV27UcMueDQJW2hFLmrG3xfZSbNlacRSEeium6s83DpIgz8JliFnVm0WLsmebjIB9UlSQz14U04Xp2uuAI6awwPS5e/xBKDckvFUnhloHiQIE2cs2jrdkEDlJ7NFhA25Jp2040Y/Bld4+pjsP9lshEzGS0eJLt9W5+ESv7cO4RbXy8w+6yFD/r3/lxhHq/xs5eE5J0vFLlQNPVtST/kpMWvylIGVKdQWQBFu01FRPT7j6NPxOAPayldrfMiG8Z16Atga6sbBIUC6OEGmctN++zKWKK/KmUFmiNSJkPV8lSx+CY84wGGaqT72ZpqlscdAJe/G31RE6uzuG1AxbuQqr/xzTOSuUfLsj1FZrKVvx7TVJR4iNkrQQzyEPSuRzRJ9a2qKzBzSnqgUZ0xmbr140PpSk1D1DRISGYIrun165Vzqu6XgUMaFQKTpdPMNu1GAM+8UruQf+1NdE= karl"

    # Default root disk size
    zk_vm_disks:
      - name: "{{ zk_vm_name }}-root"
        dev: vda
        size: 20G

zk_kvm_hosts:
  hosts:
    dell:
      connection_user: root
      ansible_host: 10.5.0.100
      zk_kvm_data_dir: /zk-data
      zk_kvm_memballoon_mem_limit_mb: 16000
      zk_kvm_networks:
        - name: br105
          subnet: 10.5.0.0/16
          nic_type: bridge
          nic_source: br105
          nic_device_model: virtio
          nic_bus: 13
          netplan:
            dhcp4: false
            dhcp6: false
            routes:
              - to: 0.0.0.0/0
                via: 10.5.0.1
            nameservers:
              addresses:
                - 1.1.1.1

infra:
  hosts:
    r2d2:
      ansible_host: 10.5.1.10
      zk_vm_name: r2d2
      zk_vm_image: debian12
      zk_vm_kvm_hosts: dell
      zk_vm_memory_mb: 2000
      zk_vm_vcpus: 1
      zk_vm_disks:
        - name: "{{ zk_vm_name }}-root"
          dev: vda
          size: 20G
      zk_vm_networks:
        - name: br105
          netplan:
            addresses: [10.5.1.10/16]
    github-runner:
      ansible_host: 10.5.1.11
      zk_vm_name: github-runner
      zk_vm_image: debian12
      zk_vm_kvm_hosts: dell
      zk_vm_memory_mb: 2000
      zk_vm_vcpus: 1
      zk_vm_disks:
        - name: "{{ zk_vm_name }}-root"
          dev: vda
          size: 20G
      zk_vm_networks:
        - name: br105
          netplan:
            addresses: [10.5.1.11/16]
    zk-testkvm:
      ansible_host: 10.5.1.12
      zk_vm_name: zk-testkvm
      zk_vm_image: debian12
      zk_vm_kvm_hosts: dell
      zk_vm_memory_mb: 8000
      zk_vm_vcpus: 2
      zk_vm_disks:
        - name: "{{ zk_vm_name }}-root"
          dev: vda
          size: 200G
      zk_vm_networks:
        - name: br105
          netplan:
            addresses: [10.5.1.12/16]

k8s:
  children:
    k8s-controllers:
      vars:
        zk_vm_image: debian12
        zk_vm_memory_mb: 3000
        zk_vm_vcpus: 1
        zk_vm_disks:
          - name: "{{ zk_vm_name }}-root"
            dev: vda
            size: 40G
      hosts:
        k8s-controller1:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.1
          zk_vm_name: k8s-controller1
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.1/16]
        k8s-controller2:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.2
          zk_vm_name: k8s-controller2
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.2/16]
        k8s-controller3:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.3
          zk_vm_name: k8s-controller3
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.3/16]
    k8s-workers:
      vars:
        zk_vm_image: debian12
        zk_vm_memory_mb: 6000
        zk_vm_vcpus: 3
        zk_vm_disks:
          - name: "{{ zk_vm_name }}-root"
            dev: vda
            size: 100G
      hosts:
        k8s-worker1:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.11
          zk_vm_name: k8s-worker1
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.11/16]
        k8s-worker2:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.12
          zk_vm_name: k8s-worker2
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.12/16]
        k8s-worker3:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.13
          zk_vm_name: k8s-worker3
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.13/16]
        k8s-worker4:
          zk_vm_kvm_hosts: dell
          ansible_host: 10.5.150.14
          zk_vm_name: k8s-worker4
          zk_vm_networks:
            - name: br105
              netplan:
                addresses: [10.5.150.14/16]

