---
apiVersion: v2
name: kube-prometheus-stack
version: 0.1.1

dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 58.3.1
    alias: kube-prometheus-stack

