---
apiVersion: v2
name: kube-prometheus-stack
version: 0.1.1

dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    # 58.3 bug: https://github.com/prometheus-community/helm-charts/pull/4503
    version: 60.5.0
    alias: kube-prometheus-stack

