---
kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: "grafana-admin-creds"
      userKey: user
      passwordKey: password
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki-gateway.loki.svc.cluster.local
        access: proxy
