---
ingress-wan:
  controller:
    extraArgs:
      default-ssl-certificate: cert-manager/wildcard-tls
      enable-ssl-passthrough: true
    ingressClassResource:
      name: ingress-wan
      default: false
    service:
      loadBalancerIP: "10.5.150.102"
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
    replicaCount: 3
