---
- hosts: zk
  gather_facts: false
  roles:
    - karlivory.zk.provision
  tags: [zk]

- hosts: all
  roles:
    - common
  tags: [common]

- hosts: k8s-workers
  roles:
    - k8s-worker
  tags: [k8s]

- hosts: github-runner
  roles:
    - github-runner
  tags: [github-runner]
