ingresses:
  - name: grafana-ingress
    namespace: kube-prometheus-stack
    host: grafana.homelab.karlivory.dev
    externalDnsTarget: ingress1.homelab.karlivory.dev
    ingressClassName: ingress1
    service:
      name: kube-prometheus-stack-grafana
      port: 80

# kubectl get ns -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | awk '{print "  - "$0}'
namespaces:
  - argocd
  - bind9
  - cert-manager
  - core-resources
  - default
  - external-dns
  - ingress1
  - k0s-autopilot
  - kube-node-lease
  - kube-prometheus-stack
  - kube-public
  - kube-system
  - loki
  - longhorn
  - metallb
  - promtail
  - reloader
  - whoami
