ingresses:
  - name: argocd-ingress
    namespace: argocd
    host: argocd.homelab.karlivory.dev
    externalDnsTarget: ingress-lan.homelab.karlivory.dev
    ingressClassName: ingress-lan
    service:
      name: argocd-server
      port: 80
  - name: grafana-ingress
    namespace: kube-prometheus-stack
    host: grafana.homelab.karlivory.dev
    externalDnsTarget: ingress-lan.homelab.karlivory.dev
    ingressClassName: ingress-lan
    service:
      name: kube-prometheus-stack-grafana
      port: 80

# kubectl get ns -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | awk '{print "  - "$0}'
namespaces:
  - argocd
  - cert-manager
  - core-resources
  - default
  - external-dns
  - ingress-lan
  - ingress-wan
  - k0s-autopilot
  - kube-node-lease
  - kube-prometheus-stack
  - kube-public
  - kube-system
  - loki
  - longhorn
  - metallb
  - promtail
  - reloader
  - whoami

